packages:
  - 'apps/*'
  - 'libs/*'

autoInstallPeers: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - esbuild
  - msgpackr-extract
  - nx
  - prisma
  - sharp
  - unrs-resolver
